#!/bin/zsh
# $1 is the log file generated by the compilation process

echo ${2:=0} > /dev/null

luts=`cat $1\_batch.prj/solution1/impl/vhdl/report/$1\_utilization_routed.rpt | grep "Slice LUTs"  | cut -d "|" -f 3 | sed "s/\ //g"`
regs=`cat $1\_batch.prj/solution1/impl/vhdl/report/$1\_utilization_routed.rpt | grep "Slice Registers"  | cut -d "|" -f 3 | sed "s/\ //g"`
dsps=`cat $1\_batch.prj/solution1/impl/vhdl/report/$1\_utilization_routed.rpt | grep "DSPs"  | cut -d "|" -f 3 | sed "s/\ //g"`
bram36=`cat $1\_batch.prj/solution1/impl/vhdl/report/$1\_utilization_routed.rpt | grep "RAMB36/FIFO36"  | cut -d "|" -f 3 | sed "s/\ //g"`
bram18=`cat $1\_batch.prj/solution1/impl/vhdl/report/$1\_utilization_routed.rpt | grep "RAMB18/FIFO18"  | cut -d "|" -f 3 | sed "s/\ //g"`

if [[ $2 -eq 0 ]]; then
	echo $1, LUTs=$luts, REGs=$regs, DSPs=$dsps, BRAM36=$bram36, BRAM18=$bram18
else
	echo \'$luts\', \'$regs\', \'$dsps\', \'$bram36\', \'$bram18\'
fi 
